### ISSUE TITLE
Class 'Barryvanveen\Lastfm\LastfmServiceprovider' not found

### ISSUE THREAD

**Issue by PitchRE** [barryvanveen/lastfm#2]
## Detailed description

After installing package via composer, I cannot propery initialize package in laravel app.

`  Class 'Barryvanveen\Lastfm\LastfmServiceprovider' not found  `

Yes I added package to providers.
`
    'providers' => [

        /*
         * Laravel Framework Service Providers...
         */
        Illuminate\Auth\AuthServiceProvider::class,
        Illuminate\Broadcasting\BroadcastServiceProvider::class,
        Illuminate\Bus\BusServiceProvider::class,
        Illuminate\Cache\CacheServiceProvider::class,
        Illuminate\Foundation\Providers\ConsoleSupportServiceProvider::class,
        Illuminate\Cookie\CookieServiceProvider::class,
        Illuminate\Database\DatabaseServiceProvider::class,
        Illuminate\Encryption\EncryptionServiceProvider::class,
        Illuminate\Filesystem\FilesystemServiceProvider::class,
        Illuminate\Foundation\Providers\FoundationServiceProvider::class,
        Illuminate\Hashing\HashServiceProvider::class,
        Illuminate\Mail\MailServiceProvider::class,
        Illuminate\Notifications\NotificationServiceProvider::class,
        Illuminate\Pagination\PaginationServiceProvider::class,
        Illuminate\Pipeline\PipelineServiceProvider::class,
        Illuminate\Queue\QueueServiceProvider::class,
        Illuminate\Redis\RedisServiceProvider::class,
        Illuminate\Auth\Passwords\PasswordResetServiceProvider::class,
        Illuminate\Session\SessionServiceProvider::class,
        Illuminate\Translation\TranslationServiceProvider::class,
        Illuminate\Validation\ValidationServiceProvider::class,
        Illuminate\View\ViewServiceProvider::class,
        Collective\Html\HtmlServiceProvider::class,
        UniSharp\LaravelFilemanager\LaravelFilemanagerServiceProvider::class,
        Intervention\Image\ImageServiceProvider::class,
        Barryvanveen\Lastfm\LastfmServiceprovider::class,
`
I know package wasn't updated in two years . 
I use newest laravel version.

**Comment by barryvanveen** [comment]
There is a typo in the readme, the casing is wrong. If you replace `LastfmServiceprovider` with `LastfmServiceProvider` (capital P) it should all work. I will update the readme later when I have more time :)

**Comment by PitchRE** [comment]
That's you for fast response. Everything works now!
Also I would want to Thank you for creating that package. Its very useful. Thanks you.
